config/routes.rb
Demo::Application.routes.draw do
  get "answer/new_answer"
  get "answer/show_answers"
  
  get "test/new_test"
  get "test/questions"
  get "test/evaluation"
  get "test/testlist"
  get "login/show_login"
  get "login" => "login#create_login", as: "create_login"
  

  delete "logout" => "login#logout", as: "logout"

  post "login" => "login#create_login", as: "login"

  get "login/logout"

  
  resources :users, only: [:new, :create]
  get "lessons" => "lessons#view_lessonsList", as: "lessons"
  
  get "lessons/:id/tests" => "lessons#tests", as: "lesson_tests"

  get "lessons/:id" => "lessons#view_lesson", as: "lesson"
  get "lessons/:id/tests/:test_id/questions" => "lessons#questions", as: "questions"

  get "lessons/:id/tests/:test_id/questions" => "lessons#answers", as: "answers"

  get "lessons/view_test"
  get "lessons/view_evaluation"

  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
	belongs_to :question
	
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
	has_many :tests, dependent: :destroy
	has_many :questions, through: :tests
	validates :thema, presence: true
	validates :content, presence: true
	validates :autor, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many :answers
	belongs_to :test
end

app/models/test.rb
class Test < ActiveRecord::Base
	has_many :questions, dependent: :destroy
	has_many :answers , :through => :questions
end

app/models/user.rb
class User < ActiveRecord::Base
	#has_many :lessons

	has_secure_password

	validates :email,
		format: /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i,
		uniqueness: true
end

app/controllers/answer_controller.rb
class AnswerController < ApplicationController
  def new_answer
  end

  def show_answers
  	@lesson = Lesson.find(params[:id])
   # @tests = @lesson.tests

  	@test = @lesson.tests(params[:test_id])
   # @questions = @test.questions

  	@question = @test.questions(params[:question_id])
    @answers = @question.answers
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
	def current_user
		if session[:user_id]
			@current_user ||= User.find(session[:user_id])
		end
	end


	def user_signed_in?
		current_user.present?
	end


		helper_method :user_signed_in?
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  before_filter :require_login!

  def view_lessonsList
  	@lesson = Lesson.all

  end

  def view_lesson
  	@lesson = Lesson.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = Prawn::Document.new
        pdf.text @lesson.content
        send_data pdf.render, filename: "lesson_#{@lesson}.pdf", 
        type: "application/pdf", 
        disposition: "inline"
      end
      
    end
  end

  def view_test
  end

  def view_evaluation
    @question = questions.find(params[:question_id])
    @answers = @question.answers
  end

  def tests
    @lesson = Lesson.find(params[:id])
    @tests = @lesson.tests
  end

  def questions
    @test = tests.find(params[:test_id])
    @questions = @test.questions
    
    
  end

  def answers
    @question = questions.find(params[:question_id])
    @answers  = @question.answers
    
  end

	private
		def lesson_params
			params.require(:lesson).permit("thema",
			"content", "autor")
		end

    private
      def require_login!
        unless user_signed_in?
            redirect_to login_path,
            alert: "Bitte melden Sie sich zuerst an."
          end
    end


    private
    def test_params
      params.require(:test).permit("name", "level", "lesson_id")
    end

    def question_params
      params.require(:question).permit("content", "autor", "test_id")
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def show_login
  end

  def create_login

  	user = User.find_by_email(params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to lessons_path,
			notice: "Sie haben sich angemeldet"

		else
			flash.now.alert = "Fehlerhafte E-Mail-Adresse oder Passwort"
			render action: "show_login"
		end

  end

  def logout
  	session[:user_id] = nil
		redirect_to login_path,
		notice: "Sie haben sich ausgeloggt."
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def show_questions
  end

  def update_questions
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def new_test
  	@test = Test.new
  end

  def show_test

  	
  end

  def questions
   @test = Test.find(params[:id])
   @questions = @test.questions
  end

  def evaluation
  end

  private
		def test_params
			params.require(:test).permit("name", "level", "lesson_id")
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
		@user = User.new
	end

  def create
		@user = User.new(user_params)
		if @user.save
			redirect_to login_path,
			notice: "Ihr Benutzerkonto wurde angelegt!"

		else
			render "new"
		end
	end
private
	def user_params
		params.require(:user).permit(:email,
			:password_digest,
			:password,
			:password_confirmation)
	end

end

app/helpers/answer_helper.rb
module AnswerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/new_user_helper.rb
module NewUserHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answer/new_answer.html.erb
<h1>Answer#new_answer</h1>
<p>Find me in app/views/answer/new_answer.html.erb</p>

app/views/answer/show_answers.html.erb
<h1>Answer#show_answers</h1>
<p>Find me in app/views/answer/show_answers.html.erb</p>
<p>
			<% @answers.each do |q| %>
			<%= q.answer %>
			<% end %>
</p>

app/views/lessons/_content.html.erb
<div id="container">
	<div id="haupt_navi">
	 Navigation
	</div>
	<div id="anzeige"> 
		
	</div>

</div>

app/views/lessons/questions.html.erb
<div id="container">
	<div id="header"> 
		<p>Herzlich Willkommen</p>
	</div>
		<div id="haupt_navi">
	 		Navigation
		</div>
	<div id="anzeige"> 
		<h1>Questions</h1>
		
		<% @questions.each do |question| %>
		<h4>
		<%= question.content %>
		<%#= debug question.answers %>
		</h4>
		
		
			<% question.answers.each do |q| %>
			<form action="#" method="get">
			<input type="checkbox" name="answer" value="Answers">
			<%= q.answer %> <br>

			
		</form>
			<% end %>
		

		

		<% end %>
		<input type="submit" value="Bewerten">



		
		
	</div>

	<div id="footer"> 
		<p>footer</p>
	</div>

</div>

app/views/lessons/tests.html.erb
<div id="container">
	<div id="header"> 
		<p>Herzlich Willkommen</p>
	</div>
	<div id="haupt_navi">
	 Navigation
	</div>
	<div id="anzeige"> 
		<h1>Testlist </h1>
		<% @tests.each do |test| %>
		<%= link_to  test.name, questions_path(@lesson,test) %>| Level: <%= test.level%>
		<%# anzahl = Lesson.all.count%>
		<%# (6..anzahl).each do |i|%>
		<p>
		<%# Test.find_by_lesson_id(i).name  %> 
		<%# ["Level :",  Test.find_by_lesson_id(i).level] %>
		
		</p>
		<% end %>


		<%#= @lesson.test %>
	</div>
	<div id="footer"> 
		<p>footer</p>
	</div>

</div>

app/views/lessons/view_evaluation.html.erb
<h1>Lessons#view_evaluation</h1>
<p>Find me in app/views/lessons/view_evaluation.html.erb</p>

app/views/lessons/view_lesson.html.erb
<div id="container">
	<div id="header"> 
		<p>Herzlich Willkommen</p>
	</div>
	<div id="haupt_navi">
	 Navigation
	</div>
	<div id="anzeige"> 
		<h1>choosed Lesson </h1>
		<p>
		<%= @lesson.thema %>
		</p>
		<p>
			<%= @lesson.content %>
		</p>

		<p>
			<%= link_to "Test", lesson_tests_path(@lesson) %>
		</p>

		<p>
			<%= link_to "zurück zur Liste", lessons_path%>
		</p>
		
	</div>
	<div id="footer"> 
		<p>footer</p>
	</div>

</div>

app/views/lessons/view_lessonsList.html.erb
<div id="container">
	<div id="header"> 
		<p>Herzlich Willkommen</p>
	</div>
	<div id="haupt_navi">
	 Navigation
	</div>
	<div id="anzeige"> 
		<h1>Lessonslist</h1>
		<% anzahl = Lesson.all.count%>
		<% (1..anzahl).each do |i|%>
		<%= Lesson.find(i).thema %> |<%= link_to ":lesen", lesson_path(i) %>| 
		<%= link_to " pdf", lesson_path(i, format: "pdf") %><br>
		<% end %>
	</div>
	<div id="footer"> 
		<p>footer</p>
	</div>

</div>

app/views/lessons/view_test.html.erb
<h1>Lessons#view_test</h1>
<p>Find me in app/views/lessons/view_test.html.erb</p>

app/views/login/create_login.html.erb
<h1>Login#create_login</h1>
<p>Find me in app/views/login/create_login.html.erb</p>

app/views/login/logout.html.erb
<h1>Login#logout</h1>
<p>Find me in app/views/login/logout.html.erb</p>

app/views/login/show_login.html.erb
<div id="login"> 
	<fieldset id="log_fieldset">
		<legend>Login</legend>
			<%= form_tag login_path do %>
			<p>
				<%= label_tag :email %>
				<%= text_field_tag :email, params[:email] %>
			</p>
			<p>
				<%= label_tag :password %>
				<%= password_field_tag %>
			</p>
			<p><%= submit_tag "Log in" %></p>
		<% end %>

		<p><%= link_to "Benutzerkonto erstellen", new_user_path %></p>

	</fieldset>
</div>

app/views/questions/show_questions.html.erb
<h1>Questions#show_questions</h1>
<p>Find me in app/views/questions/show_questions.html.erb</p>

app/views/questions/update_questions.html.erb
<h1>Questions#update_questions</h1>
<p>Find me in app/views/questions/update_questions.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h3>Neuen Benutzer anlegen</h3>
<div id="registrieren">
	<fieldset id="reg_fieldset"> 
		<legend>Userdetails</legend>
			<%= form_for(@user) do |f| %>
			<% if @user.errors.any? %>
					<ul>
						<% @user.errors.full_messages.each do |msg| %>
								<li><%= msg %></li>
						<% end %>
				</ul>
			<% end %>
				<p>
					<%= f.label :email %>
					<%= f.text_field :email, :size => 15, :maxlength => 30 %>
				</p>
				<p>
					<%= f.label :password %>
					<%= f.password_field :password, :size => 15, :maxlength => 30 %>
				</p>
				<p>
					<%= f.label :password_confirmation, :size => 15, :maxlength => 30 %>
					<%= f.password_field :password_confirmation, :size => 15, :maxlength => 30 %>
				</p>
				<p><%= submit_tag "Registrieren", :class => "submit" %></p>
		<% end %>
	</fieldset>
</div>